name: Build PR
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.20
    steps:
    - uses: actions/checkout@v4.1.0
    - name: restore_cache
      uses: actions/cache@v4.3.0
      with:
        key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
        path: node_modules/
        restore-keys: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
    - name: Install Dependencies
      run: yarn --frozen-lockfile
    - name: Lint the codebase
      run: yarn lint
    - name: Run tests
      run: yarn test --colors --maxWorkers=2
    - name: Run build
      run: yarn build
  harness-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18.20
    env:
      executor: docker-harness
      install_manually: true
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      - name: Use Node.js 18.20.1
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18.20.1
          nvm alias default 18.20.1
      - name: Install Python and required packages
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv
      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install pipenv gunicorn
          pipenv --version  # Verify pipenv is installed
          gunicorn --version  # Verify gunicorn is installed
        if: env.install_manually
      - run: bash -c 'echo "0.0.0.0 httpbin.org" >> /etc/hosts'
        if: env.install_manually
      - run: git clone https://github.com/stoplightio/httpbin httpbin
        if: env.install_manually
      - run: |
          cd httpbin
          . ../venv/bin/activate
          pipenv requirements > requirements.txt
          pip3 install --no-cache-dir -r requirements.txt
          pip3 install --no-cache-dir ./
        if: env.install_manually
      - run: |
          cd httpbin
          . ../venv/bin/activate
          gunicorn -b 0.0.0.0:80 httpbin:app -k gevent &
          sleep 15  # Wait for the server to start
          curl -I http://0.0.0.0:80  # Test server availability
        if: env.install_manually
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Create CLI binary
        run: yarn build.binary
      - name: Run Harness
        run: yarn test.harness
